<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Lumia.Foundation.Logger</PackageId>
    <Description>Package com funcionalidades de log</Description>
    <RepositoryUrl>https://github.com/JeannAndrade/Lumia.Foundation</RepositoryUrl>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <PackageTags>LoggerService</PackageTags>
    <PackageReleaseNotes>Adicionado assinatura de warn com exception</PackageReleaseNotes>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageVersion>0.4.0</PackageVersion>
    <Authors>Jeann Andrade</Authors>
    <Company>Lumia Tech</Company>
    <Product>Lumia.Foundation</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog.Extensions.Logging" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="build\Lumia.Foundation.Logger.targets" Pack="true" PackagePath="build\Lumia.Foundation.Logger.targets" />
    <None Include="Config\nlog.config" Pack="true" PackagePath="build\Config\nlog.config" />
    <None Include="docs\readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
