<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Lumia.Foundation.Core</PackageId>
    <Description>Conjunto de classes utilitárias para projetos em C#</Description>
    <RepositoryUrl>https://github.com/JeannAndrade/Lumia.Foundation</RepositoryUrl>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <PackageTags>DateTime Entity ValueObject</PackageTags>
    <PackageReleaseNotes>**v0.10.0**: Removido os namespaces de ValueObject, pois a validação de entrada é feita via annotations.</PackageReleaseNotes>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageVersion>0.10.0</PackageVersion>
    <Authors>Jeann Andrade</Authors>
    <Company>Lumia Tech</Company>
    <Product>Lumia.Foundation.Core</Product>
  </PropertyGroup>

  <ItemGroup>
    <None Include="docs\readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
