<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Lumia.Foundation.Auth</PackageId>
    <Description>Conjunto de classes utilitárias de Autenticação para uso em projetos ASP.NET Core</Description>
    <RepositoryUrl>https://github.com/JeannAndrade/Lumia.Foundation</RepositoryUrl>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <PackageTags>ActionFilters Auth JWT Identity</PackageTags>
    <PackageReleaseNotes>Projeto de autenticação com suporte a JWT, Identity e EntityFrameworkCore.
      Inclui serviços de autenticação, gerenciamento de tokens JWT, configuração de identidade e
      persistência de dados.</PackageReleaseNotes>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageVersion>0.1.0</PackageVersion>
    <Authors>Jeann Andrade</Authors>
    <Company>Lumia Tech</Company>
    <Product>Lumia.Foundation</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.11" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="docs\readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LumiaFoundation.Logger\LumiaFoundation.Logger.csproj" />
  </ItemGroup>

</Project>